### ISSUE TITLE
Problem Running preProcess_getASEventReadCounts_step3.py

### ISSUE THREAD

**Issue by KASHISH72** [anbrooks/juncBASE#2]
Hi, 
I am running juncBASE but when I run this command on my files, I always get this error.
Please let me know what I am doing wrong
And it always stop at this point of the command

Creating tree
Processing Reads
Getting Left and Right Counts

ERROR:
Traceback (most recent call last):
  File "/Users/cherr5/Downloads/juncBASE-master/intron_exon_jctn_counts.py", line 403, in <module>
    if **name** == "**main**": main()
  File "/Users/cherr5/Downloads/juncBASE-master/intron_exon_jctn_counts.py", line 269, in main
    region_coord = getRegionCoord(line_list[2])
  File "/Users/cherr5/Downloads/juncBASE-master/intron_exon_jctn_counts.py", line 366, in getRegionCoord
    region_coord = convertCoordStr(region_coord_str)
  File "/Users/cherr5/Downloads/juncBASE-master/getASEventReadCounts.py", line 2644, in convertCoordStr
    start_str, end_str = start_end.split("-")
ValueError: too many values to unpack

Thanks,
Kashish Chetal

**Comment by anbrooks** [comment]
If the newest 1.2-beta release doesn't work, then let me know.

**Comment by dorothyzh** [comment]
I‘ve faced with the same situation, where is the 1.2-beta? I've pull down the github version, and it still failed.......


 
Traceback (most recent call last):
  File "/home/xialab/software/juncBASE-master/intron_exon_jctn_counts.py", line 403, in <module>
    if __name__ == "__main__": main()
  File "/home/xialab/software/juncBASE-master/intron_exon_jctn_counts.py", line 269, in main
    region_coord = getRegionCoord(line_list[2])
  File "/home/xialab/software/juncBASE-master/intron_exon_jctn_counts.py", line 366, in getRegionCoord
    region_coord = convertCoordStr(region_coord_str)
  File "/home/xialab/software/juncBASE-master/getASEventReadCounts.py", line 2644, in convertCoordStr
    start_str, end_str = start_end.split("-")
ValueError: too many values to unpack



Thanks,

Huan ZHONG

**Comment by anbrooks** [comment]
1.2-beta can be found under the Github repo releases: https://github.com/anbrooks/juncBASE/releases/tag/v1.2-beta

Are you still receiving the error? It might be due to chromosome or scaffold names that contain certain characters. This is a bug that is still being worked on.

**Comment by dorothyzh** [comment]
Thanks, ?I've tried it again with 1.2 beta version, and the bug still existed.......


Huan




________________________________
发件人: anbrooks <notifications@github.com>
发送时间: 2017年1月20日 13:11
收件人: anbrooks/juncBASE
抄送: Zhong, Huan; Comment
主题: Re: [anbrooks/juncBASE] Problem Running preProcess_getASEventReadCounts_step3.py (#2)


1.2-beta can be found under the Github repo releases: https://github.com/anbrooks/juncBASE/releases/tag/v1.2-beta

Are you still receiving the error? It might be due to chromosome or scaffold names that contain certain characters. This is a bug that is still being worked on.

―

**Comment by sneha100895** [comment]
Hi, 

I am using the 1.2-beta version and I am also getting the same error.
Did you manage to fix it?

Sneha
