### ISSUE TITLE
An error: ImportError: No module named rpy2.robjects

### ISSUE THREAD

**Issue by maofengbiao** [anbrooks/juncBASE#4]
/nfs/turbo/med-dou-lab/soft/anaconda2/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
/nfs/turbo/med-dou-lab/soft/anaconda2/lib/python2.7/site-packages/numpy/lib/function_base.py:586: VisibleDeprecationWarning: using a boolean instead of an integer will result in an error in the future
  tmp_a = tmp_a[keep]
Not supporting deletions, yet e.g., 12M1D39M
Not supporting insertions, yet e.g., 35M1I14M
Traceback (most recent call last):
  File "/nfs/turbo/med-dou-lab/soft/juncBASE/plotEntropyScores.py", line 400, in <module>
    if __name__ == "__main__": main()
  File "/nfs/turbo/med-dou-lab/soft/juncBASE/plotEntropyScores.py", line 151, in main
    label="junction entropy")
  File "/nfs/turbo/med-dou-lab/soft/anaconda2/lib/python2.7/site-packages/matplotlib/pyplot.py", line 2965, in hist
    stacked=stacked, data=data, **kwargs)
  File "/nfs/turbo/med-dou-lab/soft/anaconda2/lib/python2.7/site-packages/matplotlib/__init__.py", line 1819, in inner
    return func(ax, *args, **kwargs)
  File "/nfs/turbo/med-dou-lab/soft/anaconda2/lib/python2.7/site-packages/matplotlib/axes/_axes.py", line 5985, in hist
    m, bins = np.histogram(x[i], bins, weights=w[i], **hist_kwargs)
  File "/nfs/turbo/med-dou-lab/soft/anaconda2/lib/python2.7/site-packages/numpy/lib/function_base.py", line 589, in histogram
    tmp_a_data = tmp_a.astype(float)
ValueError: could not convert string to float: K
/nfs/turbo/med-dou-lab/soft/anaconda2/lib/python2.7/site-packages/numpy/lib/function_base.py:586: VisibleDeprecationWarning: using a boolean instead of an integer will result in an error in the future
  tmp_a = tmp_a[keep]
Not supporting deletions, yet e.g., 39M1D11M
Not supporting insertions, yet e.g., 27M1I4M
Traceback (most recent call last):
  File "/nfs/turbo/med-dou-lab/soft/juncBASE/plotEntropyScores.py", line 400, in <module>
    if __name__ == "__main__": main()
  File "/nfs/turbo/med-dou-lab/soft/juncBASE/plotEntropyScores.py", line 151, in main
    label="junction entropy")
  File "/nfs/turbo/med-dou-lab/soft/anaconda2/lib/python2.7/site-packages/matplotlib/pyplot.py", line 2965, in hist
    stacked=stacked, data=data, **kwargs)
  File "/nfs/turbo/med-dou-lab/soft/anaconda2/lib/python2.7/site-packages/matplotlib/__init__.py", line 1819, in inner
    return func(ax, *args, **kwargs)
  File "/nfs/turbo/med-dou-lab/soft/anaconda2/lib/python2.7/site-packages/matplotlib/axes/_axes.py", line 5985, in hist
    m, bins = np.histogram(x[i], bins, weights=w[i], **hist_kwargs)
  File "/nfs/turbo/med-dou-lab/soft/anaconda2/lib/python2.7/site-packages/numpy/lib/function_base.py", line 589, in histogram
    tmp_a_data = tmp_a.astype(float)
ValueError: could not convert string to float: K
/nfs/turbo/med-dou-lab/soft/anaconda2/lib/python2.7/site-packages/numpy/lib/function_base.py:586: VisibleDeprecationWarning: using a boolean instead of an integer will result in an error in the future
  tmp_a = tmp_a[keep]
Not supporting deletions, yet e.g., 39M1D11M
Not supporting insertions, yet e.g., 27M1I4M

**Comment by maofengbiao** [comment]
ValueError: could not convert string to float: K /?

**Comment by maofengbiao** [comment]
IndexError: list index out of range
Traceback (most recent call last):
  File "/nfs/turbo/med-dou-lab/soft/juncBASE/pairwise_fishers_test_getASEvents_w_reference.py", line 19, in <module>
    import rpy2.robjects as robjects
ImportError: No module named rpy2.robjects
Traceback (most recent call last):
  File "/nfs/turbo/med-dou-lab/soft/juncBASE/buildVirtualReference_median.py", line 16, in <module>
    import rpy2.robjects as robjects
ImportError: No module named rpy2.robjects
Traceback (most recent call last):
  File "/nfs/turbo/med-dou-lab/soft/juncBASE/buildVirtualReference_median.py", line 16, in <module>
    import rpy2.robjects as robjects
ImportError: No module named rpy2.robjects
Traceback (most recent call last):
  File "/nfs/turbo/med-dou-lab/soft/juncBASE/buildVirtualReference_median.py", line 16, in <module>
    import rpy2.robjects as robjects
ImportError: No module named rpy2.robjects
Traceback (most recent call last):
  File "/nfs/turbo/med-dou-lab/soft/juncBASE/buildVirtualReference_median.py", line 16, in <module>
    import rpy2.robjects as robjects
ImportError: No module named rpy2.robjects
